### ISSUE TITLE
keyerror URL

### ISSUE THREAD

**Issue by sapare542** [SHIVANIUM-GIT/fyers-api-totp#1]
Traceback (most recent call last):
  File "/Users/ravisekharsapare/stocks/fyers-api-totp/fyerstotp.py", line 111, in <module>
    url = authres['Url']
KeyError: 'Url'

**Comment by sapare542** [comment]
authres does not have the URL as key, so thats why its failing.

**Comment by SHIVANIUM-GIT** [comment]
we are updating the project wait

**Comment by SHIVANIUM-GIT** [comment]
please clone again
